# Generated by Django 3.1.2 on 2020-10-11 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
