# Generated by Django 3.1.2 on 2020-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0002_auto_20201011_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='full_domain_name',
            field=models.CharField(max_length=253, unique=True),
        ),
    ]
