# Generated by Django 3.1.2 on 2020-10-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0003_auto_20201015_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='domain',
        ),
        migrations.AddField(
            model_name='url',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diffresults.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
