# Generated by Django 3.1.2 on 2020-10-15 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0004_auto_20201015_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_name',
            field=models.CharField(default='Test URL', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.CharField(max_length=2048, validators=[django.core.validators.URLValidator(['http', 'https'])]),
        ),
    ]
