# Generated by Django 3.1.2 on 2020-11-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0005_auto_20201015_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.CharField(max_length=256, verbose_name='name')),
                ('header_value', models.CharField(max_length=256, verbose_name='value')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffresults.url')),
            ],
        ),
    ]
