# Generated by Django 3.1.2 on 2020-11-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0006_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='method',
            field=models.CharField(default='GET', max_length=256, verbose_name='method'),
        ),
    ]
