# Generated by Django 3.1.2 on 2020-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0008_auto_20201105_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_fetched_date',
            field=models.DateTimeField(null=True, verbose_name='date last fetched'),
        ),
    ]
