# Generated by Django 3.1.2 on 2020-11-06 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0009_url_last_fetched_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='fetch_frequency',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), 'Every half hour'), (datetime.timedelta(seconds=21600), 'Six hours, every day'), (datetime.timedelta(days=1), 'Daily'), (datetime.timedelta(days=7), 'Weekly'), (datetime.timedelta(seconds=300), 'Every five minutes'), (datetime.timedelta(seconds=60), 'Every minute'), (datetime.timedelta(seconds=3600), 'Hourly')], default=datetime.timedelta(days=1), verbose_name='fetch frequency'),
        ),
        migrations.AlterField(
            model_name='url',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='request body'),
        ),
        migrations.AlterField(
            model_name='url',
            name='last_fetched_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date last fetched'),
        ),
    ]
