# Generated by Django 3.1.2 on 2020-11-07 06:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0010_auto_20201106_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='file_ext',
            field=models.CharField(default='txt', max_length=16, verbose_name='file extension'),
        ),
        migrations.AddField(
            model_name='url',
            name='filename',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='url',
            name='fetch_frequency',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), 'Daily'), (datetime.timedelta(seconds=60), 'Every minute'), (datetime.timedelta(seconds=21600), 'Six hours, every day'), (datetime.timedelta(days=7), 'Weekly'), (datetime.timedelta(seconds=1800), 'Every half hour'), (datetime.timedelta(seconds=3600), 'Hourly'), (datetime.timedelta(seconds=300), 'Every five minutes')], default=datetime.timedelta(days=1), verbose_name='fetch frequency'),
        ),
    ]
