# Generated by Django 3.1.2 on 2020-11-24 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0013_task_attempt_count'),
        ('diffresults', '0013_auto_20201124_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='fetch_frequency',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=60), 'Every minute'), (datetime.timedelta(seconds=3600), 'Hourly'), (datetime.timedelta(seconds=1800), 'Every half hour'), (datetime.timedelta(days=1), 'Daily'), (datetime.timedelta(seconds=21600), 'Six hours, every day'), (datetime.timedelta(days=7), 'Weekly'), (datetime.timedelta(seconds=300), 'Every five minutes')], default=datetime.timedelta(days=1), verbose_name='fetch frequency'),
        ),
        migrations.AlterField(
            model_name='url',
            name='file_ext',
            field=models.CharField(choices=[('js', 'js'), ('xml', 'xml'), ('txt', 'txt'), ('html', 'html')], default='txt', max_length=16, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='url',
            name='scheduled_task',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.schedule'),
        ),
    ]
