version: '3'

services:
    webhawk:
        build: .
        container_name: webhawk
        volumes:
            - static_volume:/static
        expose:
            - 8000
        build:
            context: .
            args:
                DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    nginx:
        image: nginx:1.19
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./conf/nginx:/etc/nginx/conf.d
            - static_volume:/static
        depends_on:
            - webhawk

volumes:
    static_volume:

