# Generated by Django 3.1.2 on 2020-11-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffresults', '0017_auto_20201124_2208'),
        ('django_q', '0013_task_attempt_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='url',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='diffresults.url'),
        ),
    ]
